/**
 *  jssm's ESLint 10 flat config — the fsl#545 lint revival.
 *
 *  Design decisions of record (fsl#545, #727–#732, decided 2026-07-11):
 *   - typescript-eslint recommendedTypeChecked is the centerpiece; the strict
 *     tier is deferred until the fsl#712 tsconfig-strict migration (v7 era).
 *   - eslint-plugin-fp is dead (2017); replaced by eslint-plugin-functional's
 *     lite tier, which respects jssm's intentionally mutable machine core.
 *   - eslint-plugin-new-with-error is superseded by unicorn/throw-new-error.
 *   - eslint-plugin-react was dropped: jssm ships lit-flavored web components,
 *     no React runtime, no JSX.
 *   - Tests are linted syntax-only (they are historically untyped; the build
 *     tsconfig omits them) plus @vitest/eslint-plugin hygiene rules.
 *   - Build scripts (src/buildjs, CommonJS) get node-scoped rules via
 *     eslint-plugin-n and no type-aware rules.
 *
 *  Type information comes from tsconfig.eslint.json, a lint-only project that
 *  widens the build tsconfig to all of src/ts.
 */

import eslint     from '@eslint/js';
import tseslint   from 'typescript-eslint';
import unicorn    from 'eslint-plugin-unicorn';
import promise    from 'eslint-plugin-promise';
import functional from 'eslint-plugin-functional';
import importX    from 'eslint-plugin-import-x';
import regexp     from 'eslint-plugin-regexp';
import jsdoc      from 'eslint-plugin-jsdoc';
import vitest     from '@vitest/eslint-plugin';
import n          from 'eslint-plugin-n';
import globals    from 'globals';



export default tseslint.config(

  {
    ignores: [
      'src/ts/fsl_parser.ts',        // PEG-generated; never hand-edited
      'src/ts/version.ts',           // build-stamped by makever.cjs
      'src/ts/fsl_docs_content.ts',  // generated by build_help_content.cjs
      'src/ts/tests/generated/**',   // build-produced test artifacts
    ],
  },

  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },



  //  library + component surface: full type-aware tier
  //
  {
    files: ['src/ts/**/*.ts'],

    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      unicorn.configs.recommended,
      promise.configs['flat/recommended'],
      regexp.configs['flat/recommended'],
      importX.flatConfigs.recommended,
      importX.flatConfigs.typescript,
      jsdoc.configs['flat/recommended-typescript'],
    ],

    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        project         : './tsconfig.eslint.json',
        tsconfigRootDir : import.meta.dirname,
      },
    },

    settings: {
      'import-x/resolver': { typescript: true, node: true },
    },

    rules: {

      //  jssm's snake_case filenames and short-identifier house style are
      //  deliberate; these unicorn rules exist to impose the opposite
      'unicorn/filename-case'         : 'off',
      'unicorn/prevent-abbreviations' : 'off',
      'unicorn/name-replacements'     : 'off',
      'unicorn/consistent-boolean-name': 'off',
      'unicorn/max-nested-calls'      : 'off',

      //  null is a first-class citizen of the jssm data model
      'unicorn/no-null': 'off',

      //  the arrow tables stack empty case groups with blank lines between
      //  visual clusters; empty fallthrough is the intent
      'no-fallthrough': ['error', { allowEmptyCase: true }],

      //  UNSOUND pre-strict: boolean-annotated fields legitimately hold
      //  undefined (tsconfig strict is off until fsl#712), so `x === false`
      //  is tri-state logic and rewriting it to `!x` changes behavior — the
      //  autofix for this rule broke allows_override and cost 13 tests
      'unicorn/no-unnecessary-boolean-comparison': 'off',

      //  emit target is es2017: toSorted/toReversed do not exist there
      'unicorn/no-array-sort'   : 'off',
      'unicorn/no-array-reverse': 'off',

      //  wc define entry points assign registration handles onto window by design
      'unicorn/no-global-object-property-assignment': 'off',

      //  real finding but invasive to fix; revisit in a dedicated cleanup
      'unicorn/consistent-function-scoping': 'warn',

      //  the Machine class's _underscore members are deliberate house style;
      //  #private fields change runtime semantics (own-property behavior,
      //  brand checks), which is not a lint chore's call to make
      'unicorn/prefer-private-class-fields': 'off',

      //  member layout in the big classes groups by feature, not by kind;
      //  reordering hundreds of members is churn without safety value
      'unicorn/consistent-class-member-order': 'off',

      //  the wc *.define.ts entry points exist precisely for their
      //  registration side effect; cdn/iife surfaces likewise
      'unicorn/no-top-level-side-effects': 'off',

      //  house style is point-free where possible: named functions are
      //  passed to array methods by reference on purpose
      'unicorn/no-array-callback-reference': 'off',

      //  import shape is dictated by the rollup/dts pipeline, not preference
      'unicorn/import-style': 'off',

      //  emit target is es2017 (lib es2020): iterator helpers, Set methods,
      //  String.replaceAll (es2021), Array.at (es2022) and friends do not
      //  exist in the supported runtimes — these rules raise the consumer
      //  runtime floor, which is a semver decision, not a lint fix
      'unicorn/prefer-iterator-to-array'    : 'off',
      'unicorn/prefer-iterator-helpers'     : 'off',
      'unicorn/prefer-set-methods'          : 'off',
      'unicorn/prefer-top-level-await'      : 'off',
      'unicorn/prefer-string-replace-all'   : 'off',
      'unicorn/prefer-at'                   : 'off',

      //  Promise.withResolvers is es2024 (Node >= 22); the CI matrix still
      //  carries a Node 20 leg, so this rule is a floor-raiser too — its
      //  autofix broke the Node 20 leg on jssm#939
      'unicorn/prefer-promise-with-resolvers': 'off',

      //  charCodeAt→codePointAt changes surrogate-pair behavior, which the
      //  unicode suites pin; that conversion deserves its own pass under the
      //  full unicode gauntlet, not a ride-along on a lint chore
      'unicorn/prefer-code-point': 'off',

      //  house style embraces reduce and point-free array pipelines
      'unicorn/no-array-reduce': 'off',

      //  the no-unsafe family presupposes tsconfig strict; jssm pins
      //  strict:false until the fsl#712 migration (deferred to the v7 era).
      //  On a pre-strict codebase these are the strict migration by proxy —
      //  they come back on with #712, not before.
      '@typescript-eslint/no-unsafe-argument'     : 'off',
      '@typescript-eslint/no-unsafe-assignment'   : 'off',
      '@typescript-eslint/no-unsafe-call'         : 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return'       : 'off',

      //  pre-strict reality: anys are legion and already tagged TODO FIXME;
      //  they fall to the #712 strict migration, not a lint chore
      '@typescript-eslint/no-explicit-any': 'off',

      //  deliberately off in the old config; the unused-var debt is tangled
      //  with whargarbl-marked code and belongs to a dedicated pass
      'no-unused-vars'                    : 'off',
      '@typescript-eslint/no-unused-vars' : 'off',

      //  guard-then-interpolate narrows the interpolated value to never in
      //  the throw branch; that pattern is deliberate in the error messages
      '@typescript-eslint/restrict-template-expressions': ['error', {
        allowNumber: true, allowBoolean: true, allowNever: true,
      }],

      //  house DocBlock policy: params/returns are documented when they add
      //  clarity, never as boilerplate — completeness is review-enforced;
      //  @throws names the error type in prose, not {braces}
      'jsdoc/require-param'       : 'off',
      'jsdoc/require-returns'     : 'off',
      'jsdoc/require-jsdoc'       : 'off',
      'jsdoc/require-throws-type' : 'off',

      //  load-bearing non-JSDoc tags: the custom-elements-manifest analyzer
      //  vocabulary (feeds custom-elements.json) and the vitest environment
      //  pragma (jsdom opt-in per test file)
      'jsdoc/check-tag-names': ['warn', {
        definedTags: [
          'element', 'attribute', 'attr', 'csspart', 'cssproperty', 'slot',
          'vitest-environment',
        ],
      }],

    },
  },



  //  functional lite tier on the hand-written library core only — the machine
  //  internals are intentionally mutable, so the rules that outlaw mutation,
  //  loops, lets, and throws are disabled with cause: mutation and rollback
  //  are the runtime's architecture, throws are the 5.x error model, and
  //  loops were a recorded fp/no-loops opt-out even in the eslint-4 era.
  //  What survives of lite gets locked in so it stays true.
  //
  {
    files: ['src/ts/*.ts'],
    extends: [functional.configs.lite],
    rules: {
      'functional/immutable-data'         : 'off',
      'functional/prefer-immutable-types' : 'off',
      'functional/no-let'                 : 'off',
      'functional/no-loop-statements'     : 'off',
      'functional/no-return-void'         : 'off',
      'functional/no-throw-statements'    : 'off',

      //  jssm's public API records mix data and callables by design (state
      //  metadata beside hook slots); splitting them is a v9 hook-registry-era
      //  decision, not a lint chore. Arity/currying rules likewise.
      'functional/no-mixed-types'         : 'off',
      'functional/functional-parameters'  : 'off',
      'functional/no-class-inheritance'   : 'off',
    },
  },



  //  tests (all suites: core, wc, cm6): syntax tier + vitest hygiene; no
  //  type-aware rules (tests are outside the build tsconfig and historically
  //  untyped), no functional tier
  //
  {
    files: ['src/ts/**/tests/**/*.ts'],
    extends: [
      tseslint.configs.disableTypeChecked,
      vitest.configs.recommended,
    ],
    rules: {
      'jsdoc/require-jsdoc': 'off',

      //  genuine hygiene findings, but fixing them reshapes dozens of tests;
      //  kept visible as warnings for a dedicated test-cleanup follow-up
      'vitest/no-conditional-expect' : 'warn',
      'vitest/no-commented-out-tests': 'warn',

      //  tests legitimately require() built artifacts under vitest's cjs
      //  interop (bundle-shape checks, dist smoke tests)
      '@typescript-eslint/no-require-imports': 'off',
      'unicorn/prefer-module'                : 'off',
    },
  },



  //  build scripts: CommonJS under node, no type-aware rules.
  //  The n version is pinned here to what maintainers actually run, because
  //  package.json engines still claims node >=10 — a decade-stale statement
  //  that must be corrected as its own deliberate (consumer-facing) decision,
  //  not smuggled into a lint chore. These scripts are repo-internal.
  //
  {
    files: ['src/buildjs/**/*.cjs', 'src/buildjs/**/*.js'],
    extends: [
      eslint.configs.recommended,
      n.configs['flat/recommended-script'],
    ],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    settings: {
      n: { version: '>=22.0.0' },
    },
    rules: {
      //  build scripts exit with meaningful codes on purpose; that is their
      //  contract with CI
      'n/no-process-exit': 'off',
    },
  }

);
