declare function arr_uniq_p<T>(el: T, i: number, source: T[]): boolean;
declare const array_box_if_string: (n: any) => any;
declare const weighted_rand_select: Function;
declare const seq: Function;
declare const histograph: Function;
declare const weighted_sample_select: Function;
declare const weighted_histo_key: Function;
declare const hook_name: (from: string, to: string) => string;
declare const named_hook_name: (from: string, to: string, action: string) => string;
export { seq, arr_uniq_p, histograph, weighted_histo_key, weighted_rand_select, weighted_sample_select, array_box_if_string, hook_name, named_hook_name };
