
import { defineConfig } from 'vitest/config';

/**
 * Docblock-example suite — runs the `*.docex.ts` files generated by
 * `src/buildjs/extract_examples.cjs` from `@example` blocks.  Uses the jsdom
 * environment as a superset so `jssm_viz` examples can run.  Emits metrics
 * into `./coverage/docs/`.
 */
export default defineConfig({

  test: {

    name              : 'docs',
    globals           : true,
    environment       : 'jsdom',
    include           : ['src/ts/tests/generated/**/*.docex.ts'],
    exclude           : ['**/node_modules/**', '**/dist/**', '.claude/**'],

    setupFiles        : ['./vitest.setup.ts'],

    reporters         : [
      'default',
      ['./src/buildjs/vitest_metrics_reporter.cjs', {
        outputDir  : './coverage/docs',
        outputFile : 'metrics.json'
      }]
    ],

    coverage: {

      provider          : 'v8',
      enabled           : true,
      reportsDirectory  : './coverage/docs',
      reporter          : ['text', 'clover', 'lcov', 'html', 'json'],

      include           : ['src/ts/**/*.{js,ts}'],
      exclude           : [
        'node_modules/**',
        'src/ts/tests/**',
        'src/ts/wc/tests/**',
        'src/ts/fsl_parser.ts',
        'src/ts/fsl_parser.js'
      ],

      thresholds: {
        branches   : 0,
        functions  : 0,
        lines      : 0,
        statements : 0
      }

    },

    testTimeout       : 30_000,
    hookTimeout       : 30_000

  }

});
