import { from } from '../../../jssm';
import { TypegenError } from '../../types';

/**
 * Options accepted by {@link typegen}.
 *
 * `target` selects the host declaration language. v1 emits TypeScript only;
 * other hosts (C headers, …) land later through the same target-plugin seam
 * as `codegen` (megaspec §25), so the option exists now to keep call sites
 * stable.
 *
 * `name` is the identifier the emitted declarations are built around (the
 * states union becomes `<Name>State`, the machine surface becomes
 * `<Name>Machine`, …). It defaults to `'Machine'`.
 */
export interface TypegenOptions {
  /** Host declaration language. Only `'typescript'` is supported in v1. */
  target?: TypegenTarget;
  /** Base identifier for the emitted declarations. Default: `'Machine'`. */
  name?: string;
}

/**
 * Declaration-language targets supported by `typegen`. TypeScript first —
 * TS users are the largest consumer constituency (megaspec §25); other hosts
 * are added later through the same target seam as `codegen`.
 */
export type TypegenTarget = 'typescript';

/**
 * The structured type surface extracted from a machine, before it is
 * rendered to a host language. Kept as data so additional targets render the
 * same facts without re-parsing.
 */
export interface TypeSurface {
  /** Every state name in the machine. */
  states: string[];
  /** The action alphabet — every named action (transition label). */
  actions: string[];
  /** Declared property names (the typed-value surface deepens once `val` lands). */
  props: string[];
  /** The machine's start state. */
  initial: string;
}

/**
 * Extract the {@link TypeSurface} of a machine from its FSL source.
 *
 * This is the parse step shared by every `typegen` target: it builds the
 * machine once and reads its introspection surface (states, action alphabet,
 * property names, start state). It deliberately produces *no* host language —
 * rendering is the target's job.
 *
 * @param fsl - FSL source text.
 * @returns The machine's type surface as plain data.
 * @throws TypegenError if the FSL fails to parse.
 *
 * @example
 *   const surface = extractTypeSurface("a 'go' -> b;");
 *   // surface.states  === ['a', 'b']
 *   // surface.actions === ['go']
 *   // surface.initial === 'a'
 */
export function extractTypeSurface(fsl: string): TypeSurface {
  let machine: ReturnType<typeof from>;
  try {
    machine = from(fsl);
  } catch (e) {
    throw new TypegenError(`typegen parse failed: ${(e as Error).message ?? String(e)}`);
  }
  return {
    states:  machine.states().map(String),
    actions: machine.list_actions().map(String),
    props:   machine.known_props(),
    initial: String(machine.state()),
  };
}

/**
 * Render a list of names as a TypeScript string-literal union, or `never`
 * when the list is empty (the correct bottom type for "no members").
 *
 * @param names - The literal members of the union.
 * @returns A TypeScript type expression: `'a' | 'b'`, or `never` if empty.
 *
 * @example
 *   literalUnion(['a', 'b']);  // "'a' | 'b'"
 *   literalUnion([]);          // "never"
 */
function literalUnion(names: string[]): string {
  if (names.length === 0) return 'never';
  return names.map(n => `'${n.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`).join(' | ');
}

/**
 * Render a {@link TypeSurface} as a TypeScript declaration (`.d.ts`-style)
 * module: union types for the states and the action alphabet, a property-name
 * union, and an interface describing the machine's typed surface for its
 * *callers*.
 *
 * This is the declaration-only artifact — it carries no implementation. It is
 * the `typegen` analogue of a hand-written `.d.ts`: a consumer of the machine
 * imports these types to compile against the machine's surface without
 * depending on how the machine is built.
 *
 * @param surface - The extracted type surface.
 * @param name - Base identifier for the emitted declarations.
 * @returns TypeScript declaration source text.
 *
 * @example
 *   const ts = renderTypeScript({ states: ['a','b'], actions: ['go'], props: [], initial: 'a' }, 'Light');
 *   // ts contains: export type LightState = 'a' | 'b';
 */
function renderTypeScript(surface: TypeSurface, name: string): string {
  const statesUnion  = literalUnion(surface.states);
  const actionsUnion = literalUnion(surface.actions);
  const propsUnion   = literalUnion(surface.props);

  const lines: string[] = [];
  lines.push(`// Generated by \`fsl typegen\` — declarations only, no implementation.`);
  lines.push(`// The type surface a consumer of this machine compiles against.`);
  lines.push('');
  lines.push(`/** Every state in the machine. */`);
  lines.push(`export type ${name}State = ${statesUnion};`);
  lines.push('');
  lines.push(`/** The action alphabet — every named transition action. */`);
  lines.push(`export type ${name}Action = ${actionsUnion};`);
  lines.push('');
  lines.push(`/** Declared property names (the typed-value surface deepens once \`val\` lands). */`);
  lines.push(`export type ${name}Prop = ${propsUnion};`);
  lines.push('');
  lines.push(`/** The machine's start state. */`);
  lines.push(`export type ${name}Initial = '${surface.initial.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}';`);
  lines.push('');
  lines.push(`/** The typed surface a caller compiles against. */`);
  lines.push(`export interface ${name} {`);
  lines.push(`  state(): ${name}State;`);
  lines.push(`  action(action: ${name}Action): boolean;`);
  lines.push(`  prop(name: ${name}Prop): unknown;`);
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Emit the *type surface* of a machine as host-language declarations — the
 * `.d.ts` of a machine, distinct from `codegen`'s implementation. `typegen`
 * types the machine for its *callers*; `codegen` emits the machine itself.
 *
 * @param fsl - FSL source text.
 * @param opts.target - Host declaration language. Only `'typescript'` in v1.
 * @param opts.name - Base identifier for the declarations. Default: `'Machine'`.
 * @returns Declaration source text for the requested target.
 * @throws TypegenError on parse failure or an unsupported target.
 *
 * @example
 *   const decls = typegen("a 'go' -> b;", { name: 'Light' });
 *   // decls contains: export type LightState = 'a' | 'b';
 *   //                 export type LightAction = 'go';
 */
export function typegen(fsl: string, opts: TypegenOptions = {}): string {
  const target = opts.target ?? 'typescript';
  const name   = opts.name ?? 'Machine';
  const surface = extractTypeSurface(fsl);
  switch (target) {
    case 'typescript':
      return renderTypeScript(surface, name);
    default:
      throw new TypegenError(`typegen: unknown target: ${String(target)}`);
  }
}
