import { parseFslArgs } from '../../cli-utils';

const getVersion = (): string => '__JSSM_VERSION__';

const SPEC = {
  flags: {
    help:     { short: 'h' as const, boolean: true as const },
    version:  { short: 'V' as const, boolean: true as const },
  },
  usage: 'fsl-export-system-prompt [options]',
};

const writeStdout = (s: string): void => { process.stdout.write(s); };
const writeStderr = (s: string): void => { process.stderr.write(s); };

const printErr = (msg: string): void => {
  writeStderr(`fsl-export-system-prompt: error: ${msg}\n`);
};

const SYSTEM_PROMPT = `
# FSL v5 Agent System Prompt (llms.txt)

> **Context**: This document is intended to be served as an \`llms.txt\` file (as standardized by [llmstxt.org](https://llmstxt.org) and similar AI directories) to provide Large Language Models with a mathematically precise, up-to-date syntax guide for FSL (Finite State Language).

You are an expert developer in FSL (Finite State Language) v5, a domain-specific language for defining mathematically verifiable, finite state machines. Your primary goal is to generate idiomatic, structurally sound FSL v5 code.

## Core Concepts

1.  **Machines**: An FSL file defines a state machine. It contains metadata (like \`machine_name\`) and a set of state transitions.
2.  **States & Transitions**: FSL is built on transitions between states. States are automatically inferred from transitions, or can be explicitly declared.
3.  **Transition Types**:
    *   \`->\` (Legal transition)
    *   \`=>\` (Main transition)
    *   \`~>\` (Forced transition)
    *   \`<->\` (Bi-directional legal)
    *   \`<= >\` (Main left, legal right)
    *   \`<~>\` (Bi-directional forced)
4.  **Actions**: Transitions can be triggered by actions. E.g., \`A 'click' -> B;\`
5.  **Probabilities**: Transitions can carry probabilities. E.g., \`A -> 50% B;\`
6.  **Attributes**: Machines can have properties like \`machine_name\`, \`machine_author\`, \`machine_version\`.

## Syntax Guide

### Basic Machine
\`\`\`fsl
machine_name    : "Simple Traffic Light";
machine_author  : "John Doe";
machine_version : 1.0.0;

Red 'timer' => Green 'timer' => Yellow 'timer' => Red;
\`\`\`

### Actions and Multiple Targets
\`\`\`fsl
machine_name : "Vending Machine";

Off 'insert coin' -> Idle;
Idle 'select item' -> Dispensing;
Dispensing 'dispense' -> Off;
Idle 'cancel' -> Off;
\`\`\`

### Explicit State Declarations and Attributes
\`\`\`fsl
state Red {
  background-color : red;
  text-color       : white;
};

state Green {
  background-color : green;
};

Red -> Green;
\`\`\`

## Agent Directives
- **Do not hallucinate features**: FSL is a strict, finite state machine language. Do not attempt to use unbounded loops or syntax from general-purpose languages like Python or JavaScript.
- **Always output valid FSL**: Ensure statements end with semicolons (\`;\`).
- **Use single quotes for actions**: E.g., \`StateA 'action name' -> StateB;\`.

---
*Generated by the FSL v5 Toolchain*
`;

/**
 * The \`fsl-export-system-prompt\` plugin entry point. Exported as \`cli(argv)\` so the
 * dispatcher can invoke it in-process; also called by the binary
 * (\`fsl-export-system-prompt.ts\`) which adds the shebang.
 *
 * @param argv - Args after the subcommand name
 * @returns 0 on success, 1 on user error, 2 on internal error
 */
export async function cli(argv: string[]): Promise<number> {
  let parsed: ReturnType<typeof parseFslArgs>;
  try {
    parsed = parseFslArgs(argv, SPEC);
  } catch (e) {
    printErr((e as Error).message);
    return 1;
  }

  if (parsed.flags.help) {
    writeStdout(parsed.helpText() + '\n');
    return 0;
  }
  if (parsed.flags.version) {
    writeStdout('fsl-export-system-prompt ' + getVersion() + '\n');
    return 0;
  }

  // Output the system prompt
  writeStdout(SYSTEM_PROMPT.trim() + '\n');

  return 0;
}
