'use strict';

// Compile the help-page tree (src/help) + a trimmed teaching-surface manifest
// into a generated, committed TS content module that <fsl-docs> imports.
// See notes/superpowers/specs/2026-06-28-fsl-docs-component-design.md.

const fs = require('node:fs');
const path = require('node:path');
const { scanPages, parseFrontMatter } = require('../scripts/teaching_surface/scan_pages.cjs');

const ROOT = path.join(__dirname, '..', '..');

/** Compile help pages (with bodies) + trimmed teachable features. */
function buildHelpContent(helpDir, manifestPath) {
  const { pages: scanned } = scanPages(helpDir);
  const pages = scanned.map(p => {
    const text = fs.readFileSync(path.join(ROOT, p.source), 'utf8');
    const { body } = parseFrontMatter(text);
    return {
      id: p.id, section: p.section, title: p.title, order: p.order,
      teaches: p.teaches, mentions: p.mentions, indexTerms: p.indexTerms, body,
    };
  });
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const features = manifest.features
    .filter(f => f.tier !== 'exclude')
    .map(f => ({
      id: f.id, surface: f.surface, title: f.title, tier: f.tier,
      referenceAnchor: f.referenceAnchor, indexTerms: f.indexTerms || [],
    }));
  return { pages, features };
}

const HEADER = `// GENERATED by src/buildjs/build_help_content.cjs — do not edit.
export interface DocsPage { id: string; section: string; title: string; order: number;
  teaches: string[]; mentions: string[]; indexTerms: string[]; body: string; }
export interface DocsFeature { id: string; surface: string; title: string; tier: string;
  referenceAnchor?: string; indexTerms: string[]; }
`;

/** Write the generated `.ts` content module. */
function emit(helpDir, manifestPath, outPath) {
  const { pages, features } = buildHelpContent(helpDir, manifestPath);
  const body = HEADER +
    `export const DOCS_PAGES: DocsPage[] = ${JSON.stringify(pages, null, 2)};\n` +
    `export const DOCS_FEATURES: DocsFeature[] = ${JSON.stringify(features, null, 2)};\n`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, body);
}

module.exports = { buildHelpContent, emit };

if (require.main === module) {
  emit(
    path.join(ROOT, 'src', 'help'),
    path.join(ROOT, 'src', 'data', 'teaching-surface.json'),
    path.join(ROOT, 'src', 'ts', 'wc', 'generated', 'fsl_docs_content.ts'),
  );
  console.log('fsl_docs_content.ts generated');
}
