name: Node CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        include:
          - node-version: 15.x   # fastest, so run first, to error fast
            os: ubuntu-latest
          - node-version: 15.x
            os: macos-latest     # slowest, so run next. sort by slowest from here to get earliest end through parallelism
          - node-version: 15.x
            os: windows-latest
          - node-version: 14.x
            os: macos-latest
          - node-version: 14.x
            os: windows-latest
          - node-version: 14.x
            os: ubuntu-latest
          - node-version: 8.x
            os: ubuntu-latest
          - node-version: 10.x
            os: ubuntu-latest
          - node-version: 12.x
            os: ubuntu-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run githubaction
        npm test
      env:
        CI: true
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.github_token }}
