import type { MachineSurface } from '../surface';
import { jsStringLiteralBody } from '../emit-utils';

/** Emit a string-literal union type from a list, or `never` if empty. */
function emitUnion(members: string[]): string {
  if (members.length === 0) return 'never';
  return members.map(m => `'${jsStringLiteralBody(m)}'`).join(' | ');
}

/**
 * Build the `from → { action → to }` transition table as a host object
 * literal, indented for embedding in a class body.
 */
function emitTransitionTable(surface: MachineSurface, indent: string): string {
  const byFrom = new Map<string, { action: string; to: string }[]>();
  for (const s of surface.states) byFrom.set(s, []);
  for (const t of surface.transitions) {
    // Surface states always contains every edge endpoint, so this is defined.
    byFrom.get(t.from)!.push({ action: t.action, to: t.to });
  }

  const stateLines = surface.states.map(state => {
    const edges = byFrom.get(state)!;
    const edgeBody = edges
      .map(e => `${indent}    '${jsStringLiteralBody(e.action)}': '${jsStringLiteralBody(e.to)}'`)
      .join(',\n');
    const inner = edges.length === 0 ? '{}' : `{\n${edgeBody}\n${indent}  }`;
    return `${indent}  '${jsStringLiteralBody(state)}': ${inner}`;
  });

  return `{\n${stateLines.join(',\n')}\n${indent}}`;
}

/**
 * Emit a self-contained TypeScript implementation of a compiled machine: the
 * `native:javascript` shape plus exported `State`/`Action` string-literal
 * union types and full method signatures, so the generated machine is typed
 * for its host the way a hand-written one would be. This is the
 * `native:typescript` target.
 *
 * @param surface - The extracted machine surface
 * @param symbol - The class name to emit (state/action types derive from it)
 * @returns TypeScript source text (a module exporting `symbol` and its types)
 *
 * @example
 *   const src = emitNativeTypescript(
 *     { states: ['a','b'], initial: 'a', actions: ['go'],
 *       transitions: [{ from: 'a', action: 'go', to: 'b' }] },
 *     'Demo'
 *   );
 *   // src contains "export type DemoState = 'a' | 'b'"
 */
export function emitNativeTypescript(surface: MachineSurface, symbol: string): string {
  const table       = emitTransitionTable(surface, '  ');
  const stateType   = `${symbol}State`;
  const actionType  = `${symbol}Action`;
  return `// Generated by \`fsl codegen --target native:typescript\`. Do not edit by hand.
// A self-contained, dependency-free implementation of the source machine.

export type ${stateType} = ${emitUnion(surface.states)};
export type ${actionType} = ${emitUnion(surface.actions)};

export class ${symbol} {
  static readonly states: readonly ${stateType}[] = [${surface.states.map(s => `'${jsStringLiteralBody(s)}'`).join(', ')}];
  static readonly actions: readonly ${actionType}[] = [${surface.actions.map(a => `'${jsStringLiteralBody(a)}'`).join(', ')}];

  private static readonly transitions: Readonly<Record<${stateType}, Partial<Record<${actionType}, ${stateType}>>>> = ${table};

  private current: ${stateType} = '${jsStringLiteralBody(surface.initial)}';

  /** The current state. */
  get state(): ${stateType} {
    return this.current;
  }

  /** The action names fireable from the current state. */
  actions(): ${actionType}[] {
    return Object.keys(${symbol}.transitions[this.current]) as ${actionType}[];
  }

  /** Whether \`name\` can fire from the current state. */
  can(name: ${actionType}): boolean {
    return Object.prototype.hasOwnProperty.call(${symbol}.transitions[this.current], name);
  }

  /** Fire \`name\`; advances state and returns true, or returns false if not allowed. */
  action(name: ${actionType}): boolean {
    const next = ${symbol}.transitions[this.current][name];
    if (next === undefined) return false;
    this.current = next;
    return true;
  }
}
`;
}
