import type { MachineSurface } from '../surface';
import { jsStringLiteralBody } from '../emit-utils';

/**
 * Build the `from → { action → to }` transition table as a host object
 * literal, indented for embedding in a class body.
 */
function emitTransitionTable(surface: MachineSurface, indent: string): string {
  const byFrom = new Map<string, { action: string; to: string }[]>();
  for (const s of surface.states) byFrom.set(s, []);
  for (const t of surface.transitions) {
    // Surface states always contains every edge endpoint, so this is defined.
    byFrom.get(t.from).push({ action: t.action, to: t.to });
  }

  const stateLines = surface.states.map(state => {
    const edges = byFrom.get(state);
    const edgeBody = edges
      .map(e => `${indent}    '${jsStringLiteralBody(e.action)}': '${jsStringLiteralBody(e.to)}'`)
      .join(',\n');
    const inner = edges.length === 0 ? '{}' : `{\n${edgeBody}\n${indent}  }`;
    return `${indent}  '${jsStringLiteralBody(state)}': ${inner}`;
  });

  return `{\n${stateLines.join(',\n')}\n${indent}}`;
}

/**
 * Emit a self-contained JavaScript (ES module) implementation of a compiled
 * machine: a class whose `state` getter, `actions()`, `can(action)`, and
 * `action(name)` reproduce the machine's transition behavior with no runtime
 * dependency. This is the `native:javascript` target — FSL cross-compiled to
 * plain JS.
 * @param surface - The extracted machine surface
 * @param symbol - The class name to emit
 * @returns JavaScript source text (an ES module exporting `symbol`)
 * @example
 *   const src = emitNativeJavascript(
 *     { states: ['a','b'], initial: 'a', actions: ['go'],
 *       transitions: [{ from: 'a', action: 'go', to: 'b' }] },
 *     'Demo'
 *   );
 *   // src contains "export class Demo" and a transitions table
 */
export function emitNativeJavascript(surface: MachineSurface, symbol: string): string {
  const table     = emitTransitionTable(surface, '  ');
  const eventless = '{' + surface.eventless.map(e => `'${jsStringLiteralBody(e.from)}': '${jsStringLiteralBody(e.to)}'`).join(', ') + '}';
  return `// Generated by \`fsl codegen --target native:javascript\`. Do not edit by hand.
// A self-contained, dependency-free implementation of the source machine.

export class ${symbol} {
  static states = [${surface.states.map(s => `'${jsStringLiteralBody(s)}'`).join(', ')}];
  static actions = [${surface.actions.map(a => `'${jsStringLiteralBody(a)}'`).join(', ')}];
  static finals = [${surface.finals.map(s => `'${jsStringLiteralBody(s)}'`).join(', ')}];

  static #transitions = ${table};
  static #eventless = ${eventless};

  #state = '${jsStringLiteralBody(surface.initial)}';

  /** The current state. */
  get state() {
    return this.#state;
  }

  /** The action names fireable from the current state. */
  actions() {
    return Object.keys(${symbol}.#transitions[this.#state] ?? {});
  }

  /** Whether \`name\` can fire from the current state. */
  can(name) {
    return Object.prototype.hasOwnProperty.call(${symbol}.#transitions[this.#state] ?? {}, name);
  }

  /** Fire \`name\`; advances state and returns true, or returns false if not allowed. */
  action(name) {
    const next = (${symbol}.#transitions[this.#state] ?? {})[name];
    if (next === undefined) return false;
    this.#state = next;
    return true;
  }

  /** Whether the current state is a final (terminal or complete) state. */
  isFinal() {
    return ${symbol}.finals.includes(this.#state);
  }

  /** Take the eventless/automatic transition from the current state, if any. */
  step() {
    const next = ${symbol}.#eventless[this.#state];
    if (next === undefined) return false;
    this.#state = next;
    return true;
  }
}
`;
}
